pipeline{
  agent{label "!built-in"}
  tools{
    nodejs "Nodejs"
  }
  stages{
    stage("clone"){
      steps{
        git url: "https://github.com/bvsaikr/Angular-10-Spring-Boot-CRUD-Full-Stack-App.git"
      }
    }
    stage("unitest"){
      steps{
      nodejs("Nodejs"){
            sh 'echo "unittest"'
      }
      }
    }
    stage("build"){
      steps{
        dir("angular-frontend"){
        sh 'sudo docker build -t febuild .'
      }
      }
    }
  }
}
