pipeline{
  agent{label "!built-in"}
  tools{
    nodejs "Nodejs"
  }
  stages{
    stage("clone"){
      steps{
        git url: "https://github.com/bvsaikr/Angular-10-Spring-Boot-CRUD-Full-Stack-App.git"
      }
    }
    stage("unitest"){
      steps{
            sh 'ng test --no-watch --code-coverage'
      }
    }
    stage("build"){
      steps{
        sh 'sudo docker build -t febuild .
      }
    }
  }
}
